#!/bin/bash

# This is a thin wrapper around voyacoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using voyacoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_VOYACOIND

# Grab the value of $REAL_VOYACOINCLI which may be voyacoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_VOYACOINCLI}" "$@" | sed 's/\r//'
